# Generated by Django 4.2.1 on 2024-12-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['-time_create'], 'verbose_name': 'героя', 'verbose_name_plural': 'герои'},
        ),
        migrations.AddField(
            model_name='hero',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='адрес страницы'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='content',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликован?'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновления'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='заголовок'),
        ),
        migrations.AddIndex(
            model_name='hero',
            index=models.Index(fields=['-time_create'], name='maininfo_he_time_cr_9e8280_idx'),
        ),
    ]
