# Generated by Django 4.2.1 on 2024-12-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0002_alter_hero_options_hero_slug_alter_hero_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='адрес страницы'),
        ),
    ]
