# Generated by Django 4.2.1 on 2024-12-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0003_alter_hero_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='lines',
            field=models.ManyToManyField(related_name='heroes', to='maininfo.line'),
        ),
    ]
