# Generated by Django 4.2.1 on 2024-12-30 13:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0004_line_hero_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='описание'),
        ),
    ]
