# Generated by Django 4.2.1 on 2024-12-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0005_alter_hero_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heroes', to='maininfo.bo'),
        ),
    ]
