# Generated by Django 4.2.1 on 2024-12-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0006_bo_hero_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='price',
            new_name='bo',
        ),
    ]
