# Generated by Django 4.2.1 on 2024-12-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0007_rename_price_hero_bo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bo',
            name='price',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='bo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heroes', to='maininfo.bo'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликован?'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='lines',
            field=models.ManyToManyField(db_index=True, related_name='heroes', to='maininfo.line'),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
