# Generated by Django 4.2.1 on 2024-12-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0008_alter_bo_price_alter_hero_bo_alter_hero_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
