# Generated by Django 4.2.1 on 2024-12-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0009_hero_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
