# Generated by Django 4.2.1 on 2024-12-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0011_alter_line_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
