# Generated by Django 4.2.1 on 2024-12-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0013_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='alt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
