# Generated by Django 4.2.1 on 2025-01-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0014_hero_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/icons/lines'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='alt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
