# Generated by Django 4.2.1 on 2025-01-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maininfo', '0017_alter_introslide_image_alter_line_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['-time_create'], 'verbose_name': 'герой', 'verbose_name_plural': 'герои'},
        ),
        migrations.AlterModelOptions(
            name='introslide',
            options={'verbose_name': 'слайд в интро', 'verbose_name_plural': 'слайды в интро'},
        ),
        migrations.AddField(
            model_name='hero',
            name='is_meta',
            field=models.BooleanField(default=False, verbose_name='метовый?'),
        ),
    ]
